### ISSUE TITLE
Stuck in "Exporting primary IDB", waited for a long time with no progress.

### ISSUE THREAD

**Issue by Jacky-LinPeng** [google/bindiff#36]
## device Info
- Mac Mini - Apple M1 - Sonoma 14.0
- BinDiff 8

## screenshot

![image](https://github.com/google/bindiff/assets/15797691/56f2a8fc-2eb5-4b3c-9464-86594ff495d1)
![image](https://github.com/google/bindiff/assets/15797691/c8e03871-22d5-4f25-9796-e01b5d23623e)

## Mark
These are two small test programs I wrote, and I wanted to compare the differences using BinDiff. However, it has been stuck in the 'Exporting primary IDB' state for the past two hours, and I haven't received any results. I would appreciate your guidance on this matter.

**Comment by cblichmann** [comment]
Do you have any previous version of BinDiff installed? Can you check the output in IDA Pro's output window when you launch it? If should show both the BinDiff and BinExport plugins (can also check under `Help`|`About program` and then click on `Addons`).

You may want to manually remove old version of BinDiff and the plugins under `~/.idapro/plugins`

You could also try to separately export the binaries from IDA Pro:
- open the `.i64`
- select `Edit`|`Plugins`|`BinExport 12`
- click on `BinExport v2 binary export`

You can then use the command-line `bindiff` tool to diff them:
```bash
bindiff /path_to_primary.BinExport /path_to_secondary.BinExport
```

Afterwards you should have a .BinDiff file in the directory that you can import into the BinDiff UI.
