### ISSUE TITLE
Can subviews be reopened?

### ISSUE THREAD

**Issue by clarkewd** [google/bindiff#44]
After running a diff, if I accidentally close the Matched Functions subview is there a way to reopen it?

![subview](https://github.com/google/bindiff/assets/156377/20602180-7335-4707-8bbe-7ec4896e4cee)

I don't see any menu or plugin options for reopening the subviews. I also checked the documentation but I don't see anything there, either.

The workaround I was able to come up with was to save and load the results but I wish there was a simpler way.

![save-load](https://github.com/google/bindiff/assets/156377/cd33d982-dee6-4c59-80c2-a7074431813a)

**Comment by cblichmann** [comment]
Yes, there is :)

The BinDiff IDA Pro plugin registers a menu item for this. Just select `View`|`BinDiff`|`Matched functions`:

![Screenshot from 2024-05-30 15-10-29](https://github.com/google/bindiff/assets/213059/33788429-f3f6-4348-ba58-63c4097da3f3)

You can see all the menu items that BinDiff registers here:
https://github.com/google/bindiff/blob/main/ida/main_plugin.cc#L1210
