### ISSUE TITLE
Alternative source to acquire yFiles 2.x Java Swing?

### ISSUE THREAD

**Issue by th3-5had0w** [google/bindiff#54]
I wanted to test some features that I added to the Java GUI of bindiff, but evaluating the license from yWorks takes forever (pending)? So I wonder if there's any workaround method available or alternative source to get the license/files.

**Comment by cblichmann** [comment]
For [BinNavi](https://github.com/google/binnavi), we had a somewhat convoluted way to be able to build without the full yWorks developer license - yfileswrap

There are a couple of references there:
- https://github.com/google/binnavi/blob/master/build.xml#L87
- https://github.com/google/binnavi?tab=readme-ov-file#commercial-third-party-dependency

We never bothered to do this for BinDiff, though, and I don't know how much work this would be for the BinDiff UI. Ultimately, I want to replace the Swing UI with something web based (embedded in Java via a WebView maybe).

So I'm afraid, I don't have a good answer for you. If you want, I can try some of your changes locally.

**Comment by th3-5had0w** [comment]
Thank you, I will find some workaround for it!
